# Generated by Django 5.2.7 on 2025-10-31 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Wildberries product URL or seller profile', max_length=500)),
                ('name', models.CharField(help_text='Competitor name or identifier', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competitor',
                'verbose_name_plural': 'Competitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.IntegerField(default=10, help_text="Quantity threshold for 'Low Stock' alert")),
                ('low_rating_threshold', models.FloatField(default=4.0, help_text="Rating threshold for 'Low Rating' alert")),
                ('items_per_page', models.IntegerField(default=50, help_text='Items per page in dashboard')),
                ('default_sort', models.CharField(default='nmId', help_text='Default sort column', max_length=50)),
                ('default_sort_order', models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='asc', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='WBToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_token', models.CharField(blank=True, help_text='Content API token', max_length=255)),
                ('stats_token', models.CharField(blank=True, help_text='Statistics API token', max_length=255)),
                ('prices_token', models.CharField(blank=True, help_text='Prices API token', max_length=255)),
                ('analytics_token', models.CharField(blank=True, help_text='Analytics API token (optional)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WB Token',
                'verbose_name_plural': 'WB Tokens',
                'unique_together': {('user',)},
            },
        ),
    ]
