# Generated by Django 5.2.7 on 2025-10-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbtoken',
            name='analytics_token',
            field=models.CharField(blank=True, help_text='Analytics API token (optional)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='wbtoken',
            name='content_token',
            field=models.CharField(blank=True, help_text='Content API token', max_length=1000),
        ),
        migrations.AlterField(
            model_name='wbtoken',
            name='prices_token',
            field=models.CharField(blank=True, help_text='Prices API token', max_length=1000),
        ),
        migrations.AlterField(
            model_name='wbtoken',
            name='stats_token',
            field=models.CharField(blank=True, help_text='Statistics API token', max_length=1000),
        ),
    ]
