# Generated by Django 5.2.7 on 2025-10-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_wbtoken_analytics_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmId', models.BigIntegerField(help_text='Wildberries product ID', unique=True)),
                ('title', models.CharField(help_text='Product title', max_length=500)),
                ('brand', models.CharField(help_text='Product brand', max_length=255)),
                ('rating', models.FloatField(blank=True, help_text='Product rating (0-5)', null=True)),
                ('feedbacks', models.IntegerField(default=0, help_text='Number of feedbacks/reviews')),
                ('quantity', models.IntegerField(default=0, help_text='Stock quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price', max_digits=10, null=True)),
                ('storage_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Storage cost', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sample product should be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sample Product',
                'verbose_name_plural': 'Sample Products',
                'ordering': ['nmId'],
            },
        ),
    ]
