# Generated by Django 5.2.7 on 2025-11-01 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sampleproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(choices=[('RESTOCK', 'Restock Product'), ('CHANGE_PRICE', 'Change Price'), ('FIX_RATING', 'Fix Rating'), ('IMPROVE_LISTING', 'Improve Listing'), ('PROMOTE', 'Promote Product')], max_length=50)),
                ('advice_text', models.TextField(help_text='AI-generated advice')),
                ('priority', models.IntegerField(default=3, help_text='Priority 1-5 (1=highest)')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SHOWN', 'Shown'), ('APPLIED', 'Applied'), ('IGNORED', 'Ignored')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_advices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Advice',
                'verbose_name_plural': 'AI Advices',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Call Log',
                'verbose_name_plural': 'API Call Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('OUT_OF_STOCK', 'Out of Stock'), ('LOW_STOCK', 'Low Stock'), ('LOW_RATING', 'Low Rating'), ('DEAD_STOCK', 'Dead Stock'), ('HIGH_VALUE_AT_RISK', 'High Value at Risk')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('message', models.TextField(help_text='Alert message')),
                ('impact_score', models.FloatField(default=0.0, help_text='Impact score 0-100')),
                ('estimated_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated financial loss', max_digits=14, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Alert',
                'verbose_name_plural': 'Business Alerts',
                'ordering': ['-impact_score', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_id', models.BigIntegerField(help_text='Wildberries product ID')),
                ('title', models.CharField(help_text='Product title', max_length=500)),
                ('brand', models.CharField(help_text='Product brand', max_length=255)),
                ('category', models.CharField(help_text='Product category', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price in RUB', max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, help_text='Product rating 0-5', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('feedbacks', models.IntegerField(default=0, help_text='Number of feedbacks/reviews')),
                ('quantity', models.IntegerField(default=0, help_text='Stock quantity')),
                ('sales_7d', models.IntegerField(default=0, help_text='Sales in last 7 days')),
                ('sales_30d', models.IntegerField(default=0, help_text='Sales in last 30 days')),
                ('storage_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Storage cost', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether product is active')),
                ('is_sample', models.BooleanField(default=False, help_text='Whether this is sample data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField(help_text='Timestamp of snapshot')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('quantity', models.IntegerField()),
                ('feedbacks', models.IntegerField()),
                ('sales_7d', models.IntegerField()),
                ('sales_30d', models.IntegerField()),
                ('storage_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_status', models.CharField(help_text='Stock status at snapshot time', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.product')),
            ],
            options={
                'verbose_name': 'Product Snapshot',
                'verbose_name_plural': 'Product Snapshots',
                'ordering': ['-snapshot_at'],
            },
        ),
        migrations.DeleteModel(
            name='SampleProduct',
        ),
        migrations.AddField(
            model_name='aiadvice',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_advices', to='dashboard.businessalert'),
        ),
        migrations.AddField(
            model_name='businessalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_alerts', to='dashboard.product'),
        ),
        migrations.AddField(
            model_name='aiadvice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_advices', to='dashboard.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'nm_id'], name='dashboard_p_user_id_5a5905_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='dashboard_p_categor_6141dc_idx'),
        ),
        migrations.AddIndex(
            model_name='businessalert',
            index=models.Index(fields=['user', 'is_active', '-impact_score'], name='dashboard_b_user_id_7dc3df_idx'),
        ),
        migrations.AddIndex(
            model_name='businessalert',
            index=models.Index(fields=['alert_type', 'severity'], name='dashboard_b_alert_t_982f28_idx'),
        ),
        migrations.AddIndex(
            model_name='aiadvice',
            index=models.Index(fields=['user', 'status', 'priority'], name='dashboard_a_user_id_8de643_idx'),
        ),
        migrations.AddIndex(
            model_name='productsnapshot',
            index=models.Index(fields=['product', '-snapshot_at'], name='dashboard_p_product_4dc0e3_idx'),
        ),
    ]
